<a href="https://colab.research.google.com/github/Saujanyapokhrel/Data-Processing-Visualization/blob/main/Quiz2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 
import pandas as pd 
from scipy import stats 
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/nurfnick/Data_Viz/main/iris.csv')
df

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [3]:
df.head()

   SepalLength  SepalWidth  PedalLength  PedalWidth        Class
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [5]:
df.columns

Index(['SepalLength', 'SepalWidth', 'PedalLength', 'PedalWidth', 'Class'], dtype='object')

In [6]:
df.describe()

       SepalLength  SepalWidth  PedalLength  PedalWidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.054000     3.758667    1.198667
std       0.828066    0.433594     1.764420    0.763161
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [7]:
df.SepalLength

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLength, Length: 150, dtype: float64

In [8]:
df.SepalLength.mean

<bound method Series.mean of 0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: SepalLength, Length: 150, dtype: float64>

In [9]:
df.tail(1)

     SepalLength  SepalWidth  PedalLength  PedalWidth           Class
149          5.9         3.0          5.1         1.8  Iris-virginica

In [10]:
df_melt = df.melt(id_vars='Class',
                  value_vars= ['SepalWidth','PedalWidth'],
                  var_name = 'columns')
df_melt

              Class     columns  value
0       Iris-setosa  SepalWidth    3.5
1       Iris-setosa  SepalWidth    3.0
2       Iris-setosa  SepalWidth    3.2
3       Iris-setosa  SepalWidth    3.1
4       Iris-setosa  SepalWidth    3.6
..              ...         ...    ...
295  Iris-virginica  PedalWidth    2.3
296  Iris-virginica  PedalWidth    1.9
297  Iris-virginica  PedalWidth    2.0
298  Iris-virginica  PedalWidth    2.3
299  Iris-virginica  PedalWidth    1.8

[300 rows x 3 columns]

In [11]:
df.query('PedalLength > 5 and SepalLength < 7 ')

     SepalLength  SepalWidth  PedalLength  PedalWidth            Class
83           6.0         2.7          5.1         1.6  Iris-versicolor
100          6.3         3.3          6.0         2.5   Iris-virginica
101          5.8         2.7          5.1         1.9   Iris-virginica
103          6.3         2.9          5.6         1.8   Iris-virginica
104          6.5         3.0          5.8         2.2   Iris-virginica
108          6.7         2.5          5.8         1.8   Iris-virginica
110          6.5         3.2          5.1         2.0   Iris-virginica
111          6.4         2.7          5.3         1.9   Iris-virginica
112          6.8         3.0          5.5         2.1   Iris-virginica
114          5.8         2.8          5.1         2.4   Iris-virginica
115          6.4         3.2          5.3         2.3   Iris-virginica
116          6.5         3.0          5.5         1.8   Iris-virginica
120          6.9         3.2          5.7         2.3   Iris-virginica
124          6.7         3.3          5.7         2.1   Iris-virginica
128          6.4         2.8          5.6         2.1   Iris-virginica
132          6.4         2.8          5.6         2.2   Iris-virginica
133          6.3         2.8          5.1         1.5   Iris-virginica
134          6.1         2.6          5.6         1.4   Iris-virginica
136          6.3         3.4          5.6         2.4   Iris-virginica
137          6.4         3.1          5.5         1.8   Iris-virginica
139          6.9         3.1          5.4         2.1   Iris-virginica
140          6.7         3.1          5.6         2.4   Iris-virginica
141          6.9         3.1          5.1         2.3   Iris-virginica
142          5.8         2.7          5.1         1.9   Iris-virginica
143          6.8         3.2          5.9         2.3   Iris-virginica
144          6.7         3.3          5.7         2.5   Iris-virginica
145          6.7         3.0          5.2         2.3   Iris-virginica
147          6.5         3.0          5.2         2.0   Iris-virginica
148          6.2         3.4          5.4         2.3   Iris-virginica
149          5.9         3.0          5.1         1.8   Iris-virginica

In [12]:
df.query('PedalLength >= 1 and SepalLength <= 5 ')

     SepalLength  SepalWidth  PedalLength  PedalWidth            Class
1            4.9         3.0          1.4         0.2      Iris-setosa
2            4.7         3.2          1.3         0.2      Iris-setosa
3            4.6         3.1          1.5         0.2      Iris-setosa
4            5.0         3.6          1.4         0.2      Iris-setosa
6            4.6         3.4          1.4         0.3      Iris-setosa
7            5.0         3.4          1.5         0.2      Iris-setosa
8            4.4         2.9          1.4         0.2      Iris-setosa
9            4.9         3.1          1.5         0.1      Iris-setosa
11           4.8         3.4          1.6         0.2      Iris-setosa
12           4.8         3.0          1.4         0.1      Iris-setosa
13           4.3         3.0          1.1         0.1      Iris-setosa
22           4.6         3.6          1.0         0.2      Iris-setosa
24           4.8         3.4          1.9         0.2      Iris-setosa
25           5.0         3.0          1.6         0.2      Iris-setosa
26           5.0         3.4          1.6         0.4      Iris-setosa
29           4.7         3.2          1.6         0.2      Iris-setosa
30           4.8         3.1          1.6         0.2      Iris-setosa
34           4.9         3.1          1.5         0.1      Iris-setosa
35           5.0         3.2          1.2         0.2      Iris-setosa
37           4.9         3.1          1.5         0.1      Iris-setosa
38           4.4         3.0          1.3         0.2      Iris-setosa
40           5.0         3.5          1.3         0.3      Iris-setosa
41           4.5         2.3          1.3         0.3      Iris-setosa
42           4.4         3.2          1.3         0.2      Iris-setosa
43           5.0         3.5          1.6         0.6      Iris-setosa
45           4.8         3.0          1.4         0.3      Iris-setosa
47           4.6         3.2          1.4         0.2      Iris-setosa
49           5.0         3.3          1.4         0.2      Iris-setosa
57           4.9         2.4          3.3         1.0  Iris-versicolor
60           5.0         2.0          3.5         1.0  Iris-versicolor
93           5.0         2.3          3.3         1.0  Iris-versicolor
106          4.9         2.5          4.5         1.7   Iris-virginica

In [13]:
df.groupby(by = 'Class').mean()

                 SepalLength  SepalWidth  PedalLength  PedalWidth
Class
Iris-setosa            5.006       3.418        1.464       0.244
Iris-versicolor        5.936       2.770        4.260       1.326
Iris-virginica         6.588       2.974        5.552       2.026

In [14]:
df.groupby(by='Class').agg(['mean','median'])

                SepalLength        SepalWidth  ... PedalLength PedalWidth
                       mean median       mean  ...      median       mean median
Class                                          ...
Iris-setosa           5.006    5.0      3.418  ...        1.50      0.244    0.2
Iris-versicolor       5.936    5.9      2.770  ...        4.35      1.326    1.3
Iris-virginica        6.588    6.5      2.974  ...        5.55      2.026    2.0

[3 rows x 8 columns]